name: Hacktoberfest

on:
  pull_request:
    types: [labeled, unlabeled]
  issues:
    types: [labeled, unlabeled]

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log Master Coverage
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/SCRIPTS/hacktoberfest')
            await script({github, context, core, exec}, ["andresin87"])
            
            
