name: Hacktoberfest

on:
  pull_request:
    types: [labeled, unlabeled]
  issues:
    types: [labeled, unlabeled]

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Log Master Coverage
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context, {eventName: context.eventName,label_name: context.payload.label.name})
